import { env } from '../config/env';

export interface TurnstileVerificationResult {
  success: boolean;
  errorCodes?: string[];
  challengeTs?: string;
  hostname?: string;
}

export class TurnstileService {
  private get secretKey(): string {
    return process.env.TURNSTILE_SECRET_KEY || env.TURNSTILE_SECRET_KEY || '1x0000000000000000000000000000000AA';
  }

  /**
   * Verifies a Cloudflare Turnstile challenge token server-side.
   * Calls Cloudflare's official siteverify endpoint:
   * POST https://challenges.cloudflare.com/turnstile/v0/siteverify
   *
   * @param token The Turnstile response token generated by the client widget
   * @param remoteIp Optional client IP address
   * @returns Verification result from Cloudflare
   */
  async verifyToken(token: string, remoteIp?: string): Promise<TurnstileVerificationResult> {
    if (!token || typeof token !== 'string' || token.trim() === '') {
      return {
        success: false,
        errorCodes: ['missing-input-response'],
      };
    }

    const secret = this.secretKey;
    if (!secret) {
      throw new Error('TURNSTILE_SECRET_KEY is not configured on the server');
    }

    try {
      const response = await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          secret,
          response: token.trim(),
          ...(remoteIp ? { remoteip: remoteIp } : {}),
        }),
      });

      if (!response.ok) {
        const errorText = await response.text().catch(() => '');
        console.error('[TurnstileService] Siteverify HTTP error:', response.status, errorText);
        return {
          success: false,
          errorCodes: [`http-${response.status}`],
        };
      }

      const data = (await response.json()) as {
        success: boolean;
        'error-codes'?: string[];
        challenge_ts?: string;
        hostname?: string;
      };

      return {
        success: Boolean(data.success),
        errorCodes: data['error-codes'],
        challengeTs: data.challenge_ts,
        hostname: data.hostname,
      };
    } catch (err: unknown) {
      console.error('[TurnstileService] Network error during token verification:', err);
      return {
        success: false,
        errorCodes: ['internal-verification-error'],
      };
    }
  }
}

export const turnstileService = new TurnstileService();
