"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, Clock, UserRound, Video } from "lucide-react";
import { Button } from "@/components/ui/button";

type Appointment = { id: string; patientName: string; date: string; time: string; type: "Video" | "In-Person"; status: "CONFIRMED" | "PENDING" | "COMPLETED" | "CANCELLED" };

export default function DoctorAppointmentsPage() {
  const [appointments, setAppointments] = useState<Appointment[]>([]);
  const [tab, setTab] = useState<"upcoming" | "past">("upcoming");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { fetch("/api/doctor/appointments").then(async (response) => { if (!response.ok) throw new Error("Unable to load appointments"); const body = await response.json() as { appointments: Appointment[] }; setAppointments(body.appointments); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load appointments")).finally(() => setLoading(false)); }, []);
  const visible = useMemo(() => appointments.filter((item) => tab === "upcoming" ? item.status === "CONFIRMED" || item.status === "PENDING" : item.status === "COMPLETED" || item.status === "CANCELLED"), [appointments, tab]);
  const complete = async (id: string) => { setError(null); const response = await fetch(`/api/doctor/appointments/${id}/complete`, { method: "PATCH" }); if (!response.ok) { const body = await response.json() as { message?: string }; setError(body.message ?? "Unable to complete appointment"); return; } setAppointments((current) => current.map((item) => item.id === id ? { ...item, status: "COMPLETED" } : item)); };
  return <div className="mx-auto max-w-5xl"><div className="mb-8"><h1 className="text-3xl tracking-tight text-slate-900 sm:text-4xl">My Appointments</h1><p className="mt-2 text-base text-slate-500">Review your consultations and keep patient records current.</p></div><div className="mb-6 flex gap-2 border-b border-slate-200"><button onClick={() => setTab("upcoming")} className={`border-b-2 px-4 py-3 text-sm font-semibold ${tab === "upcoming" ? "border-cyan-600 text-cyan-700" : "border-transparent text-slate-500"}`}>Upcoming</button><button onClick={() => setTab("past")} className={`border-b-2 px-4 py-3 text-sm font-semibold ${tab === "past" ? "border-cyan-600 text-cyan-700" : "border-transparent text-slate-500"}`}>Past</button></div>{error && <p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{loading ? <p className="py-10 text-center text-sm text-slate-500">Loading appointments…</p> : visible.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-200 bg-white p-12 text-center text-sm text-slate-500">No {tab} appointments.</div> : <div className="space-y-4">{visible.map((appointment) => <article key={appointment.id} className="flex flex-col gap-4 rounded-2xl border border-slate-200/70 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-cyan-50 text-cyan-700"><UserRound className="h-5 w-5" /></span><div><h2 className="font-semibold text-slate-900">{appointment.patientName}</h2><p className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-sm text-slate-500"><span className="inline-flex items-center gap-1"><CalendarDays className="h-3.5 w-3.5" />{appointment.date}</span><span className="inline-flex items-center gap-1"><Clock className="h-3.5 w-3.5" />{appointment.time}</span><span className="inline-flex items-center gap-1"><Video className="h-3.5 w-3.5" />{appointment.type}</span></p></div></div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${appointment.status === "COMPLETED" ? "bg-emerald-50 text-emerald-700" : appointment.status === "PENDING" ? "bg-amber-50 text-amber-700" : "bg-cyan-50 text-cyan-700"}`}>{appointment.status.charAt(0) + appointment.status.slice(1).toLowerCase()}</span>{(appointment.status === "CONFIRMED" || appointment.status === "PENDING") && <Button size="sm" onClick={() => complete(appointment.id)}><CheckCircle2 className="h-4 w-4" />Mark completed</Button>}</div></article>)}</div>}</div>;
}
