"use client";

import { useEffect, useState } from "react";
import { Award, BriefcaseBusiness, Stethoscope, UserRound } from "lucide-react";
import { DOCTOR_SPECIALTIES } from "@/lib/specialties";

type DoctorProfile = { specialty: string; bio: string; qualifications: string[]; yearsExperience: number; avatarUrl: string | null };
type User = { name: string; email: string; doctorProfile?: DoctorProfile };

export default function DoctorProfilePage() {
  const [user, setUser] = useState<User | null>(null);
  useEffect(() => { fetch("/api/auth/me").then(async (response) => { if (response.ok) { const body = await response.json() as { user: User }; setUser(body.user); } }).catch(() => undefined); }, []);
  const profile = user?.doctorProfile;
  return <div className="mx-auto max-w-3xl"><div className="mb-8"><h1 className="text-3xl tracking-tight text-slate-900 sm:text-4xl">My Profile</h1><p className="mt-2 text-base text-slate-500">Your public profile is used by patients when choosing a doctor.</p></div><section className="rounded-2xl border border-slate-200/70 bg-white p-6 shadow-sm"><div className="flex items-center gap-4"><span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-cyan-100 text-cyan-700"><UserRound className="h-8 w-8" /></span><div><h2 className="text-xl font-semibold text-slate-900">Dr. {user?.name.replace(/^Dr\.\s*/, "") ?? ""}</h2><p className="text-sm text-slate-500">{user?.email}</p></div></div></section><div className="mt-6 grid gap-6"><section className="rounded-2xl border border-slate-200/70 bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-semibold text-slate-900"><Stethoscope className="h-5 w-5 text-cyan-700" />Professional details</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><div><dt className="text-xs font-semibold uppercase tracking-wider text-slate-400">Specialty</dt><dd className="mt-1 text-sm font-medium text-slate-800">{profile?.specialty ?? "Loading…"}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-wider text-slate-400">Experience</dt><dd className="mt-1 text-sm font-medium text-slate-800">{profile ? `${profile.yearsExperience} years` : "Loading…"}</dd></div></dl></section><section className="rounded-2xl border border-slate-200/70 bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-semibold text-slate-900"><BriefcaseBusiness className="h-5 w-5 text-cyan-700" />About</h2><p className="mt-4 text-sm leading-6 text-slate-600">{profile?.bio ?? "Loading your profile…"}</p></section><section className="rounded-2xl border border-slate-200/70 bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-semibold text-slate-900"><Award className="h-5 w-5 text-cyan-700" />Qualifications</h2><ul className="mt-4 space-y-2 text-sm text-slate-600">{profile?.qualifications.length ? profile.qualifications.map((qualification) => <li key={qualification}>• {qualification}</li>) : <li>No qualifications added yet.</li>}</ul></section><section className="rounded-2xl border border-dashed border-cyan-200 bg-cyan-50/40 p-6"><h2 className="text-lg font-semibold text-slate-900">Profile editing</h2><p className="mt-2 text-sm text-slate-600">Specialties supported on CuraLink: {DOCTOR_SPECIALTIES.join(", ")}. Profile editing and availability controls will save here when those provider-management workflows are enabled.</p></section></div></div>;
}
